"""Initial migration

Revision ID: c51ecaebf6a1
Revises: 
Create Date: 2024-10-30 10:33:46.656064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51ecaebf6a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_members_team_id_user_id_key', 'team_members', type_='unique')
    op.add_column('teams', sa.Column('type_subscribe', sa.String(length=255), nullable=False))
    op.drop_column('teams', 'type_subscibe')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.add_column('teams', sa.Column('type_subscibe', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('teams', 'type_subscribe')
    op.create_unique_constraint('team_members_team_id_user_id_key', 'team_members', ['team_id', 'user_id'])
    # ### end Alembic commands ###
