"""Initial migration 3

Revision ID: e7bce430f2f6
Revises: 0d783021fe7c
Create Date: 2024-10-30 10:40:06.975182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bce430f2f6'
down_revision: Union[str, None] = '0d783021fe7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('porno', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'porno')
    # ### end Alembic commands ###
